name: rs23
channels:
 - conda-forge
dependencies:
 - python=3.11
 - numpy=1.24
 - matplotlib=3.7
 - obspy=1.4
 - ipython=8.14
 - pygmt=0.9
 - openpyxl=3.1
 - geopandas=0.13
 - cartopy=0.21                 # need for obspy's built-in plotting
 - pytest=7.3
 - geographiclib=2.0
 - python-lsp-server=1.7.4
 - pyflakes=3.0.1
platforms:
 - osx-arm64                    # M1
