name: rs23
channels:
 - conda-forge
dependencies:
 - python=3.11
 - numpy=1.24
 - matplotlib=3.7
 - obspy=1.4
 - ipython=8.14
 - pygmt=0.9
 - openpyxl=3.1
 - geopandas=0.13
platforms:
 - osx-arm64                    # M1
 - win-64
