I should review my existing picks with the median stacking and see if they still make sense.
Might be cleaner to write the pick file with only e.g. 2-3 digits after the decimal point.

* Questions to ask
What's going on with the first arrival at close offsets around 1070? How should I pick it?

* "A" picks
I feel pretty good about these.
** =megashot_996_5_01=
** =megashot_997_5_01=
** =megashot_998_5_01=
** =megashot_999_5_01=
** =megashot_1000_5_01=
** =megashot_1001_5_01=
** =megashot_1002_5_01=
** =megashot_1003_5_01=
** =megashot_1004_5_01=
** =megashot_1005_5_01=
** =megashot_1006_5_01=
** =megashot_1007_5_01=
** =megashot_1008_5_01=
** =megashot_1009_5_01=
** =megashot_1010_5_01=
** =megashot_1011_5_01=
** =megashot_1012_5_01=
** =megashot_1013_5_01=
** =megashot_1014_5_01=
** =megashot_1015_5_01=
** =megashot_1016_5_01=
** =megashot_1017_5_01=
** =megashot_1018_5_01=
** =megashot_1019_5_01=
** =megashot_1020_5_01=
** =megashot_1025_5_01=
Updated w/ median.
** =megashot_1030_5_01=
Updated w/ median.
** =megashot_1045_5_01=
Updated w/ median. Very off.
** =megashot_1050_5_01=
Updated w/ median.
** =megashot_1055_5_01=
Updated w/ median.
** =megashot_1060_5_01=
Updated w/ median.
** =megashot_1065_5_01=
Made w/ median.
** =megashot_1070_5_01=
Made w/ median. Weird first arrival that comes before the main bands
at close offsets. I picked it.
** =megashot_1080_5_01=
Updated w/ median. Also confused about first arrival at close offsets.
It's not as prominent here as in 1070. I picked the most clear arrival.
** =megashot_1085_5_01=
Made w/ median. Also confusing at close offsets went with what was clearest.
** =megashot_1090_5_01=
Updated w/ median. Switched from 10/side to 5/side. Close offsets a little confusing.
** =megashot_1095_5_01=
Made w/ median.
** =megashot_1100_10_01=
** =megashot_1110_10_01=
** =megashot_1115_5_01=
** =megashot_1345_5_01=
** =megashot_1350_5_01=
Modified a bit with median stacking.
** =megashot_1355_5_01=
Could pick some more here (esp. for closer offsets).
* "B" picks
Not so sure.
** =megashot_1340_5_01=
* Still working
** =broadband_KD01_01=
Picked first arrival where clear (close offsets) from bandpass 3-15 Hz.
Need to confirm if I'm picking "real" waveforms correctly.
